---
- name: Install Prysm Beacon Node
  hosts: localhost
  become: true
  vars:
    jwt_secret_path: "/root/jwtsecret" 

  tasks:
    - name: Install Docker Compose
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Generate JWT secret for Prysm
      ansible.builtin.shell: openssl rand -hex 32 > /root/jwtsecret
      args:
        creates: "/root/jwtsecret"

    - name: Get public IP
      ansible.builtin.shell: curl http://checkip.amazonaws.com
      register: beacon_node_ip
      changed_when: false  

    - name: Create Prysm Beacon service file from template
      ansible.builtin.template:
        src: prysm-beacon.service.j2
        dest: /etc/systemd/system/prysm-beacon.service

    - name: Reload systemd, enable and start Prysm Beacon service
      block:
        - name: Reload systemd daemon
          ansible.builtin.systemd:
            daemon_reload: yes

        - name: Enable Prysm Beacon service
          ansible.builtin.systemd:
            name: prysm-beacon
            enabled: yes
            state: stopped
