---
- name: Uninstall Prysm and Zora nodes
  hosts: localhost
  become: true
  tasks:
    - name: Stop Zora Node service
      ansible.builtin.systemd:
        name: zora-node
        state: stopped
      ignore_errors: yes

    - name: Remove Zora Node service
      ansible.builtin.file:
        path: /etc/systemd/system/zora-node.service
        state: absent
      ignore_errors: yes

    - name: Remove Docker containers
      ansible.builtin.shell: |
        docker rm -f beacon-node
        docker-compose -f /root/zora-node/docker-compose.yml down
      ignore_errors: yes

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
